Valid BST
JuliaGerasymenko/Tasks pull request #8
Opened 2019-11-22 15:01 UTC by JuliaGerasymenko

https://leetcode.com/problems/validate-binary-search-tree/

2019-11-25 06:59 UTC, DzyubSpirit requested changes

2019-11-25 06:59 UTC, DzyubSpirit commented on bst.js
> +    if (!root || (!root.left && !root.right)) return true;
This will work the same
```suggestion
    if (!root) return true;
```

2019-11-25 06:59 UTC, DzyubSpirit commented on bst.js
> +var isValidBST = function(root) {
Some logic here and in the recursion is duplicated os it's possible to rewrite it like that:
```suggestion
var isValidBST = root => recursion(root, -Infinity, Infinity);
```

2019-11-25 07:03 UTC, DzyubSpirit requested changes

2019-11-25 07:03 UTC, DzyubSpirit commented on bst.js
> +    return root.val < max && root.val > min
A ternary operator can be replaced with `&&` here

2019-11-25 13:05 UTC, JuliaGerasymenko commented on bst.js
> +    if (!root || (!root.left && !root.right)) return true;
[0], [1] - edge cases

2019-11-25 14:23 UTC, DzyubSpirit commented on bst.js
> +    if (!root || (!root.left && !root.right)) return true;
What do you mean?

2019-12-02 11:25 UTC, DzyubSpirit commented on bst.js
> +    return root.val < max && root.val > min
I meant something different ;)
You can write this without ternary operators, using just `&&` operator.

2019-12-02 11:26 UTC, DzyubSpirit approved these changes
Commented here:
https://github.com/JuliaGerasymenko/Tasks/pull/8#discussion_r352544730

2019-12-05 11:12 UTC, merged